name: test-and-coverage

on: 
  push:
    branches:
    - coverage
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: Running feature tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Installing Dependencies
        uses: "docker://composer:latest"
        with:
          args: "composer install"
      - run: cp .env.example .env
      - name: Preparing Laravel
        uses: "docker://php:latest"
        with:
          args: "php artisan key:generate"
      - name: Testing 
        uses: "docker://php:latest"
        with:
          args: "php artisan test"
      - name: Coverage
        uses: "docker://php:latest"
        with:
          args: "php ./vendor/bin/phpunit --coverage-clover coverage.xml && bash <(curl -s https://codecov.io/bash)"
